export const CREATE_SCRATCH_REQUEST = "CREATE_SCRATCH_REQUEST";
export const CREATE_SCRATCH_ERROR = "CREATE_SCRATCH_ERROR";
export const CREATE_SCRATCH_SUCCESS = "CREATE_SCRATCH_SUCCESS";

export const GET_SCRATCH_REQUEST = "GET_SCRATCH_REQUEST";
export const GET_SCRATCH_ERROR = "GET_SCRATCH_ERROR";
export const GET_SCRATCH_SUCCESS = "GET_SCRATCH_SUCCESS";

export const DELETE_SCRATCH_REQUEST = "DELETE_SCRATCH_REQUEST";
export const DELETE_SCRATCH_ERROR = "DELETE_SCRATCH_ERROR";
export const DELETE_SCRATCH_SUCCESS = "DELETE_SCRATCH_SUCCESS";

